# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Makoto.WinDV2
PackageVersion: 2.5.1
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mak0t0san/WinDV2/releases/download/v2.5.1/WinDV-2.5.1-x64-Setup.exe
  InstallerSha256: 534B5026B2800CFD8F58768AA8EF79BE024DEEA15530899E1E7003D392B21789
- Architecture: x86
  InstallerUrl: https://github.com/mak0t0san/WinDV2/releases/download/v2.5.1/WinDV-2.5.1-x86-Setup.exe
  InstallerSha256: F49CAD84854C495F191A66A879AA3353EFC172930D2190EC7253F73515602C50
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-27
